---
title: "Force Sliders to Sum to 100"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(shiny)
```

```{r inputs}
sliderInput("s1", "Slider 1", min = 0, max = 100, value = 50, step = 1)
sliderInput("s2", "Slider 2", min = 0, max = 100, value = 25, step = 1)
sliderInput("s3", "Slider 3", min = 0, max = 100, value = 25, step = 1)

# when s1 changes, adjust other two to fill the remainder with the same ratio as they currently have
observeEvent(input$s1, {
  remaining <- 100 - input$s1
  p_remaining_s2 <- input$s2/(input$s2 + input$s3)
  p_remaining_s3 <- input$s3/(input$s2 + input$s3)
  updateSliderInput(inputId = "s2", value = remaining * p_remaining_s2)
  updateSliderInput(inputId = "s3", value = remaining * p_remaining_s3)
})

# when s2 changes, do the same
observeEvent(input$s2, {
  remaining <- 100 - input$s2
  p_remaining_s1 <- input$s1/(input$s1 + input$s3)
  p_remaining_s3 <- input$s3/(input$s1 + input$s3)
  updateSliderInput(inputId = "s1", value = remaining * p_remaining_s1)
  updateSliderInput(inputId = "s3", value = remaining * p_remaining_s3)
})

# when s3 changes, do the same
observeEvent(input$s3, {
  remaining <- 100 - input$s3
  p_remaining_s1 <- input$s1/(input$s1 + input$s2)
  p_remaining_s2 <- input$s2/(input$s1 + input$s2)
  updateSliderInput(inputId = "s1", value = remaining * p_remaining_s1)
  updateSliderInput(inputId = "s2", value = remaining * p_remaining_s2)
})
```

```{r outputs}
renderTable({
  data.frame(
    Slider = c("1", "2", "3", "sum"), 
    Value = c(input$s1, input$s2, input$s3, input$s1 + input$s2 + input$s3)
  )
})
```